// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8UV5vkefUngglz6k77gvLiSNw6FAE2Y',
    appId: '1:275680771651:web:30f932e033defc21671ef6',
    messagingSenderId: '275680771651',
    projectId: 'study-app-733d0',
    authDomain: 'study-app-733d0.firebaseapp.com',
    databaseURL: 'https://study-app-733d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-733d0.appspot.com',
    measurementId: 'G-7L93LZJX7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzASp_HHQaOyzwfbxDxsGrAgNWhwHb-o',
    appId: '1:275680771651:android:642f7e3c449595b3671ef6',
    messagingSenderId: '275680771651',
    projectId: 'study-app-733d0',
    databaseURL: 'https://study-app-733d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-733d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLM10DtSLMAfBeFHGhVipShabw7dvQOo',
    appId: '1:275680771651:ios:9ba59fd9fd21aacf671ef6',
    messagingSenderId: '275680771651',
    projectId: 'study-app-733d0',
    databaseURL: 'https://study-app-733d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-733d0.appspot.com',
    iosClientId: '275680771651-enn5ilrddpr0lui41ie3222uatq2mnbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLM10DtSLMAfBeFHGhVipShabw7dvQOo',
    appId: '1:275680771651:ios:9ba59fd9fd21aacf671ef6',
    messagingSenderId: '275680771651',
    projectId: 'study-app-733d0',
    databaseURL: 'https://study-app-733d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-app-733d0.appspot.com',
    iosClientId: '275680771651-enn5ilrddpr0lui41ie3222uatq2mnbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAppFlutter',
  );
}
